### ISSUE TITLE
Installing this plugin gives a missing capability error

### ISSUE THREAD

**Issue by mhughes2k** [Microsoft/moodle-repository_onenote#1]
````
Capability "repository/onenote:view" was not found! This has to be fixed in code.
line 389 of /lib/accesslib.php: call to debugging()
line 1150 of /repository/lib.php: call to has_capability()
line 3278 of /repository/lib.php: call to repository::get_instances()
line 394 of /lib/form/filemanager.php: call to initialise_filepicker()
line 8706 of /lib/adminlib.php: call to form_filemanager->__construct()
line 6995 of /lib/adminlib.php: call to admin_setting_configstoredfile->output_html()
line 6970 of /lib/adminlib.php: call to admin_output_new_settings_by_page()
line 6970 of /lib/adminlib.php: call to admin_output_new_settings_by_page()
line 6970 of /lib/adminlib.php: call to admin_output_new_settings_by_page()
line 29 of /admin/upgradesettings.php: call to admin_output_new_settings_by_page()
````

This is with version 2015012701

**Comment by jamesmcq** [comment]
Thanks Michael, Did you experience any issues during install? The one or two other people that report this issue also report a hang when installing this plugin.

**Comment by mhughes2k** [comment]
No, but the Office 365 plugin page that I had been using didn't specify all the dependencies, which only became apparent on the Moodle install plugin page.

I did also get an issue with the sharepoint link setting not letting me leave it blank following the moodle upgrade process.

**Comment by jamesmcq** [comment]
We're released some updates to help solve this issue - can you update to the latest plugin version and let me know if you are still experiencing any of the above issues? Thanks!

**Comment by jamesmcq** [comment]
Hi Michael - Going to close this for now, but if you do still encounter issues please either reopen or create a new issue. Thanks!
